# Site settings
title: Grayson King's Portfolio
description: Portfolio for full-stack developer Grayson King
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Grayson King
user_description: Hi, I'm Grayson. I am a recent graduate full-stack web developer living in Kelowna, BC. I'm an ambitious worker who's always eager to face new problems and learn new technologies, able to excel both in team and self-directed settings.
user_title: Full-Stack Web Developer
email: grayson.king065@gmail.com
twitter_username: GraysonKing
github_username:  GraysonKing
gplus_username:  GraysonKing

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
